services:
  settlement-db:
    image: mysql:8.0
    container_name: settlement-db
    environment:
      MYSQL_ROOT_PASSWORD: manager
      MYSQL_DATABASE: settlementdb
    ports:
      - "3306:3306"
    volumes:
      - settlement_data:/var/lib/mysql

  streaming-db:
    image: mysql:8.0
    container_name: streaming-db
    environment:
      MYSQL_ROOT_PASSWORD: manager
      MYSQL_DATABASE: streamingdb
    ports:
      - "3307:3306"
    volumes:
      - streaming_data:/var/lib/mysql
  
  redis:
    image: redis:7.0
    container_name: streaming-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data


  config-server:
    image: openjdk:17-jdk-slim
    container_name: config-server
    volumes:
      - ./settlement-configServer/build/libs/settlement-configServer-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    command: ["java", "-jar", "app.jar"]
    ports:
      - "9000:9000"

  eureka-server:
    image: openjdk:17-jdk-slim
    container_name: eureka-server
    volumes:
      - ./settlement-eurekaServer/build/libs/settlement-eurekaServer-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    command: ["java", "-jar", "app.jar"]
    ports:
      - "8761:8761"


  gateway:
    image: openjdk:17-jdk-slim
    container_name: gateway
    volumes:
      - ./settlement-SCG/build/libs/settlement-SCG-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    command: ["java", "-jar", "app.jar"]
    ports:
      - "8082:8082"
    depends_on:
      - config-server
      - eureka-server
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_APPLICATION_NAME: settlementSCG
      SPRING_CONFIG_IMPORT: optional:configserver:http://admin:1234@config-server:9000

  settlement-statistics:
    image: openjdk:17-jdk-slim
    container_name: settlement-statistics
    volumes:
      - ./settlement-statistics-msa/build/libs/settlement-statistics-msa-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    command: ["java", "-jar", "app.jar"]
    ports:
      - "8010:8010"
    depends_on:
      - config-server
      - eureka-server
      - settlement-db
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_APPLICATION_NAME: settlement-statistics
      SPRING_CONFIG_IMPORT: optional:configserver:http://admin:1234@config-server:9000 
  

  streaming:
    image: openjdk:17-jdk-slim
    container_name: streaming
    volumes:
      - ./streaming-msa/build/libs/streaming-msa-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    command: ["java", "-jar", "app.jar"]
    ports:
      - "8020:8020"
    depends_on:
      - config-server
      - eureka-server
      - streaming-db
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_APPLICATION_NAME: streaming
      SPRING_CONFIG_IMPORT: optional:configserver:http://admin:1234@config-server:9000
  
volumes:
  settlement_data:
  streaming_data:
  redis_data:
